version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "*"
        versions: ["0.x"]
    groups:
      firebase-dependencies:
        patterns:
          - "^firebase.*"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
