name: Automerge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Automerge Dependabot PRs
      uses: "pascalgn/automerge-action@v0.15.3"
      with:
        merge-method: "merge"
        commit-message: "auto-merge"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
